// Builds index.html (the landing page) from src/site/landing.template.html.
//
// The demo board is rendered by the SAME boardHtml() the editor and the exported page use, from
// data/example.json — so the marketing page cannot show something the tool does not produce.
// Run with --check in CI to fail when index.html is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { boardHtml } from '../src/render/page.js';
import { migrate } from '../src/core/schema.js';

// Override with BOOKTIER_REPO=... if the repo lives somewhere else.
const REPO = process.env.BOOKTIER_REPO || 'https://github.com/elevatevt/booktier';

const root = new URL('../', import.meta.url);
const template = readFileSync(new URL('src/site/landing.template.html', root), 'utf8');
const example = migrate(JSON.parse(readFileSync(new URL('data/example.json', root), 'utf8')));

// Show the ranked tiers only — an "Unranked" row is editor furniture, not a finished list.
const rankedItems = example.items.filter((i) => i.tier);
const demoDoc = {
  ...example,
  items: rankedItems,
  tiers: example.tiers.filter((t) => rankedItems.some((i) => i.tier === t.id)),  // no empty rows
  render: { ...example.render, showLabels: false },                              // covers speak
};

// inlineStyles:false keeps style attributes off the page so the landing page can carry the same
// strict CSP as the app. Tier colors ship as generated rules instead — the page runs no script,
// so there is no CSSOM fallback available here.
// Function replacers: with a string replacement, `$&`, `$'` and `$1` inside the demo markup or
// the repo URL are substitution syntax, and a book title containing one corrupts the page.
const demoMarkup = boardHtml(demoDoc, { editable: false, inlineStyles: false });
const html = template
  .replace('__DEMO__', () => demoMarkup)
  .replaceAll('__REPO__', () => REPO);

const demoCss = '/* GENERATED by tools/build-site.mjs from data/example.json. Do not edit. */\n'
  + demoDoc.tiers
      .filter((t) => demoDoc.items.some((i) => i.tier === t.id))
      .map((t) => `.demo-frame .bt-row[data-tier="${t.id}"] .bt-rowlabel{background:${t.color}}`)
      .join('\n') + '\n';
const cssOut = new URL('src/site/demo.css', root);
const currentCss = (() => { try { return readFileSync(cssOut, 'utf8'); } catch { return null; } })();

const out = new URL('index.html', root);
const current = (() => { try { return readFileSync(out, 'utf8'); } catch { return null; } })();

if (process.argv.includes('--check')) {
  if (current !== html) { console.error('index.html is stale — run: node tools/build-site.mjs'); process.exit(1); }
  if (currentCss !== demoCss) { console.error('src/site/demo.css is stale — run: node tools/build-site.mjs'); process.exit(1); }
  console.log('index.html and demo.css match their sources');
} else {
  writeFileSync(out, html);
  writeFileSync(cssOut, demoCss);
  console.log(`wrote index.html (${html.length} bytes, ${demoDoc.items.length} demo covers) and src/site/demo.css`);
}
